# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Hyphenate_test' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Hyphenate_test
    pod 'MWPhotoBrowser', '~> 2.1.2'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'SDWebImage', '~> 3.8.1'
#    pod 'Parse', '~> 1.14.2'

  target 'Hyphenate_testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Hyphenate_testUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
